# SPDX-FileCopyrightText: 2026 Christopher Boone
# SPDX-License-Identifier: Apache-2.0

name = "ZhangYeung"
version = "0.1.0"
defaultTargets = ["ZhangYeung"]
lintDriver = "batteries/runLinter"
testDriver = "ZhangYeungTest"

[leanOptions]
autoImplicit = false
relaxedAutoImplicit = false

[[require]]
name = "PFR"
git = "https://github.com/teorth/pfr"
rev = "80daaf1"

[[lean_lib]]
name = "ZhangYeung"

[[lean_lib]]
name = "ZhangYeungTest"
